# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8079/user/login
Content-Type: application/json

{"userPhone":"15623891368","userPassword":"123456"}
###

GET http://localhost:8079/user/test
Accept: application/json
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzUwMTAxMjksImlhdCI6MTU3NTAwODMyOSwidXNlcm5hbWUiOiIxNTYyMzg5MTM2OCJ9.9WEpvVAL3U3asSeb_CsUfeQGqv3nC4P4lLTVhKYPrf4
###

POST http://localhost:8079/business-type/saveBusinessType
Content-Type: application/json
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzUwMTQ5MzgsImlhdCI6MTU3NTAxMzEzOCwidXNlcm5hbWUiOiIxNTYyMzg5MTM2OCJ9.5E36teWslGv5QyIV4zXz8QeuK_KhEQXQS56M63mZ2Io

{"type":2,"remark":"test3"}
###

GET http://localhost:8079/business-type/getById?id=1
Content-Type: application/json
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzUwMTQ5MzgsImlhdCI6MTU3NTAxMzEzOCwidXNlcm5hbWUiOiIxNTYyMzg5MTM2OCJ9.5E36teWslGv5QyIV4zXz8QeuK_KhEQXQS56M63mZ2Io

###

PUT http://localhost:8079/business-type/updateById
Content-Type: application/json
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzUyNTU4MzUsImlhdCI6MTU3NTI1NDAzNSwidXNlcm5hbWUiOiIxNTYyMzg5MTM2OCJ9.8zB4ZLFuTkYG0gm-iAz1GlgjRPFzgsYcBbUKsMESe2c

{"id":1,"type":12}
###