# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8079/user/login
Content-Type: application/json

{"userPhone":"15623891368","userPassword":"123456"}

###

GET http://localhost:8079/user/test
Accept: application/json

{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzQ2NDUwNjksImlhdCI6MTU3NDY0NDg4OSwidXNlcm5hbWUiOiIxNTYyMzg5MTM2OCJ9.aXsWJ3js4L-FsFWweGfmj3gRjGlSLq-4X6Qm41gkIP4"}

###
